### PR TITLE
Allow switching out LogFilter globally

### LINKED ISSUE #33: Allow switching out default DevelopmentFilter globally
[Asserts](https://github.com/Bungeefan/logger/blob/bf2c13c30fdd9f8752748d938d23a6b81c5bcc31/lib/src/filters/development_filter.dart#L12) are expensive per [Flutter doc](https://docs.flutter.dev/perf/ui-performance#interpreting-the-graphs)

It is better to use `kDebugMode` when using Flutter (which I believe will be true for a majority of the user). Since `kDebugMode` is a constant, the compiler can optimize away the conditional check making it much faster than `assert()`.

But since this project is dart only, we cannot introduce a dependency on `package:flutter/foundation.dart` because it will break the minority of users who are dart only. So it would be the best to allow the user to switch out the implementation of the `DevelopmentFilter`.

While currently it is already possible to pass `filter` to every `Logger()` call, it is much cleaner if this can be done globally.

The proposal is to allow switching out the implementation similar to `Logger.level`.

### PR DESCRIPTION
**Pull request by yangsfang**
Fixes #33

### CODE REVIEW

**Comment by Bungeefan** [comment]
Thanks for your PR, unfortunately I am having troubles merging it, as it contains the (already merged) commit of your other pull request.
Can you please fix this?

And please use one branch per PR in the future.

**Comment by yangsfang** [comment]
> This branch has no conflicts with the base branch

I don't see any conflicts at the moment. Perhaps there was an error right after you merged the other change, and it resolved itself (as it should, because it should figure out the changes are the same and ignore the base commit similar to how git does rebase).

> it contains the (already merged) commit of your other pull request

Sorry about that. I first did the README fix and thought I didn't need a new branch. And then later I made another change and found out I needed a new branch (to allow you to merge the README change independently). I was a bit lazy so I just branched off the modified master. I'll make sure I use a new branch for each in the future.

**Comment by Bungeefan** [comment]
There is no "conflict", it's that GitHub wants to merge your 2 commits, even though the first is already on the master.
This would be resolved my creating an ugly merge commit with duplicated changes, therefore, I asked you to fix it on your branch before I am continuing merging it.

**Comment by yangsfang** [comment]
Done. Thanks.

**Comment by Bungeefan** [comment]
Thanks for fixing it, merged!

**Comment by Bungeefan** [comment]
Unfortunately, I had to revert your pull request as I found an error.
We cannot provide a static field which contains an instance of the default filter, as then the **same** filter instance will be applied to all loggers, interfering with the log level.
But we can provide static functions which can be replaced with your desired default filter.

**Pull request merged**
